config/routes.rb
Rails.application.routes.draw do
  root 'bookmarks#index'
  resources :bookmarks
  resources :types
  resources :categories
  get '/categories/:id/endpoint', to: 'categories#endpoint', as: 'endpoint'
  get '/home', to: 'home#index', as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :type
    belongs_to :category

    validates :title, presence: true
    validates :url, presence: true
    validates :type_id, presence: true
    validates :category_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord  
  has_many :sub_categories, class_name: "Category", foreign_key: "category_id", dependent: :destroy						
  belongs_to :main_category, class_name: "Category", foreign_key: "category_id", optional: true	

  has_many :bookmarks, dependent: :destroy

  before_update :update_visibility

  validates :name, presence: true

  def to_s
    name
  end

  def update_visibility
    status = self.visibility
    self.sub_categories.each do |s|
      s.visibility = status
      s.save
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :bookmarks, dependent: :destroy

    validates :name, presence: true

    def to_s
        name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

    def index
        @bookmarks = Bookmark.order(:created_at).reverse_order
    end

    def show   
    end

    def new
        @bookmark = Bookmark.new
        @type = Type.new
        @category = Category.new
        @types = Type.all
        @categories = Category.all
    end

    def edit
        @types = Type.all
        @categories = Category.all
    end

    def create
        @bookmark = Bookmark.new(bookmark_params)
        sleep 2
        respond_to do |format|
            if @bookmark.save!
                format.js { render nothing: true }
                flash.now[:notice] = 'Bookmark created!'
            else
                flash.now[:notice] = 'Bookmark could not be created'
            end
        end
    end

    def update
        respond_to do |format|
            if @bookmark.update!(bookmark_params)
                format.js { render layout: false }
                flash.now[:notice] = 'Bookmark updated!'
            else
                flash.now[:notice] = 'Bookmark could not be updated'
            end
        end
    end

    def destroy
        respond_to do |format|
            if @bookmark.destroy!
                format.js { render nothing: false }
                flash.now[:notice] = 'Bookmark deleted!'
            else
                flash.now[:notice] = 'Bookmark could not be deleted'
            end
        end
    end    

    private

    def set_bookmark
        @bookmark = Bookmark.find(params[:id])
    end

    def bookmark_params
        params.require(:bookmark).permit(:title, :url, :type_id, :category_id )
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy, :endpoint]

    def index
        @categories = Category.all
    end

    def show   
    end

    def new
        @category = Category.new
        @categories = Category.all
    end

    def edit
        @categories = Category.all
    end

    def create
        @category = Category.new(category_params)
        sleep 2
        respond_to do |format|
            if @category.save!
                format.html { redirect_to categories_path, notice: 'Category created!' }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @category.update!(category_params)
                format.html { redirect_to categories_path, notice: 'Category updated' }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        respond_to do |format|
            if @category.destroy!
                format.html { redirect_to categories_path, notice: 'Category deleted!' }
            else
                format.html { redirect_to categories_path, notice: 'Category could not be deleted' }
            end
        end
    end     

    def endpoint
        render json: @category.to_json(include: [:sub_categories, :bookmarks])
    end
    
    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name, :visibility, :category_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bookmark_by_types = Bookmark.joins(:type).group(:name).count
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
    before_action :set_type, only: [:show, :edit, :update, :destroy]

    def index
        @types = Type.all
    end

    def show   
    end

    def new
        @type = Type.new
    end

    def edit
    end

    def create
        @type = Type.new(type_params)
        sleep 2
        respond_to do |format|
            if @type.save!
                format.html { redirect_to types_path, notice: 'Type created!' }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @type.update!(type_params)
                format.html { redirect_to types_path, notice: 'Type updated!' }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        respond_to do |format|
            if @type.destroy!
                format.html { redirect_to types_path, notice: 'Type deleted!' }
            else
                format.html { redirect_to types_path, notice: 'Type could not be deleted' }
            end
        end
    end     
    
    private

    def set_type
        @type = Type.find(params[:id])
    end

    def type_params
        params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr id="bookmark-<% bookmark.id %>">
    <td><%= bookmark.id %></td>
    <td><%= bookmark.title %></td>
    <td><%= bookmark.url %></td>
    <td><%= bookmark.category %></td>
    <td><%= bookmark.type %></td>
    <div class="container">
        <td><%= link_to bookmark, remote: true, class: 'btn btn-success' do fa_icon "eye 2x" end  %></td>
        <td><%= link_to edit_bookmark_path(bookmark), remote: true, class: 'btn btn-warning' do fa_icon "edit 2x" end  %></td>
        <td><%= link_to bookmark, method: :delete, remote: true, data: { confirm: "Are you sure to delete: #{bookmark.title} ?" }, class: 'btn btn-danger' do fa_icon "trash 2x" end  %></td>    
    </div>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_with(model: @bookmark, remote: true) do |form| %>
    <% if @bookmark.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2> 
            <ul>
                <% @bookmark.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label :title, 'Your title' %>
        <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :url, 'The link' %>
        <%= form.text_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :type_id %> <br>
        <%= form.collection_select :type_id, @types, :id, :name, include_blank: 'Select Type', class: "form-control"  %>
    </div>

    <div class="form-group">
        <%= form.label :category_id %> <br>
        <%= form.collection_select :category_id, @categories, :id, :name, include_blank: 'Select Category', class: "form-control" %>
    </div>

    <div class="actions">
        <%= form.submit data: { confirm: 'Are you sure?', disable_with: 'Creating...' } %>
    </div>
<% end %>

app/views/bookmarks/_new_button.html.erb
<%= link_to 'New Bookmark', new_bookmark_path, remote: true, class: 'btn btn-info btn-lg' %>

app/views/bookmarks/_notice.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/bookmarks/_show.html.erb
<div class="container">
    <div class="card my-2">
        <div class="card-body">
          <h5 class="card-title">Title: <%= @bookmark.title%></h5>
          <h6 class="card-subtitle mb-2">Link: <%= @bookmark.url %></h6>
          <div class="container">
            <p class="card-text p-card"><strong>Category: </strong><%= @bookmark.category %></p>
            <p class="card-text p-card"><strong>Type: </strong><%= @bookmark.type %></p>
          </div>
        </div>
    </div>
</div>

app/views/bookmarks/create.js.erb
$('#bookmarks').prepend('<%= j render('bookmarks/bookmark', bookmark: @bookmark)%>');
$('#form_new').html(' ');
$('#new_button').append('<%= escape_javascript render('bookmarks/new_button') %>')
$('#notice_bookmark').append('<%= j render('bookmarks/notice') %>')

app/views/bookmarks/destroy.js.erb
$('#bookmark-<% @bookmark.id %>').remove().empty();
$('#notice_bookmark').append('<%= j render('bookmarks/notice') %>');

app/views/bookmarks/edit.js.erb
$('#form_new').html('<%= escape_javascript render('bookmarks/form') %>')
$('#new_button').html(' ');

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<div id="form_new" class="container"></div>

<div id="show_bookmark" class="container"></div>

<div id="new_button" class="container">
  <%= render 'new_button' %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Link</th>
      <th scope="col">Category</th>
      <th scope="col">Type</th>
    </tr>
  </thead>
  <tbody id="bookmarks">
    <% @bookmarks.each do |bookmark| %>
      <%= render 'bookmark', bookmark: bookmark %>
    <% end %>
  </tbody>
</table>

app/views/bookmarks/new.js.erb
$('#form_new').append('<%= escape_javascript render('bookmarks/form') %>');
$('#new_button').html(' ');

app/views/bookmarks/show.js.erb
$('#show_bookmark').html('<%= j render('bookmarks/show') %>')

app/views/bookmarks/update.js.erb
$('#form_new').html(' ');
$('#bookmark-<% @bookmark.id %>').replaceWith('<%= j render('bookmarks/bookmark', bookmark: @bookmark) %>');
$('#notice_bookmark').append('<%= j render('bookmarks/notice') %>');

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2> 
            <ul>
                <% @category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label :name, 'Create a new category' %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :visibility, 'Do you want it to be public?' %>
        <%= form.check_box :visibility %>
    </div>

    <div class="form-group">
        <%= form.label :category_id, 'Add to an existent Category' %>
        <%= form.collection_select :category_id, @categories, :id, :name, include_blank: 'Select Category', class: "form-control" %>
    </div>

    <div class="actions">
        <%= form.submit data: { disable_with: 'Creating...' } %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<div class="container py-5">
    <%= link_to 'Show', category_path(@category), class: 'btn btn-success btn-lg' %> 
    <%= link_to 'Back', categories_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/categories/index.html.erb
<h1>Bookmark Categories </h1>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Is public?</th>
        <th scope="col">SubCategory</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= category.visibility %></td>
            <td><%= category.category_id %></td>
            <td><%= link_to category, class: 'btn btn-success' do fa_icon "eye 2x" end %></td>
            <td><%= link_to edit_category_path(category), class: 'btn btn-warning' do fa_icon "edit 2x" end %></td>
            <td><%= link_to category, method: :delete, data: { confirm: "Are you sure to delete?" }, class: 'btn btn-danger' do fa_icon "trash 2x" end %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<div class="container py-5">
  <%= link_to 'New category', new_category_path , class: 'btn btn-outline-info btn-lg' %> 
  <%= link_to 'Back', bookmarks_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form', category: @category %>

<div class="container py-5">
    <%= link_to 'Back', categories_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/categories/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @category.name %>
</p>
<p>
    <strong>Is Public?:</strong>
    <%= @category.visibility %>
</p>
<p>
    <strong>Category:</strong>
    <%= @category.category_id %>
</p>

<div class="container py-3">
    <h2>Category API </h2>
    <%= link_to 'Endpoint', endpoint_path(@category), class: 'btn btn-outline-info btn-lg' %>
</div>

<div class="container py-5">
    <%= link_to 'Back', categories_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/home/index.html.erb
<h1>Bookmark Graphics</h1>

<h2 class="text-center py-4">Type distribution summarized</h2>

<div class="container my-3 pie-chart">
    <%= pie_chart @bookmark_by_types, donut: true %>  
</div>

<div class="container p-3">
    <table class="table table-chart">
        <thead>
            <tr>
                <% @bookmark_by_types.keys.each do |key| %> 
                    <th scope="col"><%= key %></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <tr>
                <% @bookmark_by_types.values.each do |value| %> 
                    <td><%= value %></td>
                <% end %>
            </tr>
        </tbody>
    </table>
</div>

<div class="container py-5">
    <%= link_to 'Back', bookmarks_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaMarcadores</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <p id="notice_bookmark"></p>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container">

      <a class="navbar-brand nav-item"><%= link_to 'Bookmarks', bookmarks_path %></a> &nbsp;
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse ml-auto" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a><%= link_to 'Types', types_path %></a> &nbsp;
          </li>
          <li class="nav-item active">
            <a><%= link_to 'Categories', categories_path %></a> &nbsp;
          </li>
          <li class="nav-item active">
            <a><%= link_to 'Graphic', home_path %></a> &nbsp;
          </li>
        </ul>
      </div>
      
  </div>
</nav>

app/views/types/_form.html.erb
<%= form_with(model: @type, local: true) do |form| %>
    <% if @type.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2> 
            <ul>
                <% @type.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label :name, 'Name type' %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="actions">
        <%= form.submit data: { disable_with: 'Creating...' } %>
    </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @types %>

<div class="container py-5">
    <%= link_to 'Show', type_path(@type), class: 'btn btn-success btn-lg' %> 
    <%= link_to 'Back', types_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/types/index.html.erb
<h1>Bookmark Types</h1>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @types.each do |type| %>
        <tr>
            <td><%= type.id %></td>
            <td><%= type.name %></td>
            <td><%= link_to type, class: 'btn btn-success' do fa_icon "eye 2x" end  %></td>
            <td><%= link_to edit_type_path(type), class: 'btn btn-warning' do fa_icon "edit 2x" end  %></td>
            <td><%= link_to type, method: :delete, data: { confirm: "Are you sure to delete it?" }, class: 'btn btn-danger' do fa_icon "trash 2x" end  %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<div class="container py-5">
  <%= link_to 'New type', new_type_path, class: 'btn btn-outline-info btn-lg' %> 
  <%= link_to 'Back', bookmarks_path, class: 'btn btn-outline-dark btn-lg' %>
</div>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @type.name %>
</p>

<div class="container py-5">
    <%= link_to 'Back', types_path, class: 'btn btn-outline-dark btn-lg' %>
</div>